services:
  - type: web
    name: script-to-book
    env: docker
    rootDir: .
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: server/Dockerfile
    envVars:
      - { key: PORT, value: 4000 }


